'use strict'

export default [
  {value: 'hash', title: 'Hash'},
  {value: 'host', title: 'Host'},
  {value: 'hostname', title: 'Host Name'},
  {value: 'href', title: 'Href'},
  {value: 'origin', title: 'Origin'},
  {value: 'pathname', title: 'Pathname'},
  {value: 'protocol', title: 'Protocol'},
  {value: 'search', title: 'Search'},
  {value: 'loadId', title: 'Load Id'},
  {value: 'subid', title: 'SubId'},
  {value: 'ua', title: 'User Agent'},
  {value: 'version', title: 'Version'},
  {value: 'script', title: 'Script'},
  {value: 'pid', title: 'Product Id'},
  {value: 'strategy', title: 'Strategy'},
  {value: 'type', title: 'Type'},
  {value: 'timezoneOffset', title: 'Timezone Offset'},
  {value: 'tsClient', title: 'Ts Client'},
  {value: 'id', title: 'ID'},
  {value: 'date', title: 'Date'},
  {value: 'hour', title: 'Hour'},
  {value: 'ts', title: 'TS'},
  {value: 'level', title: 'Level'},
  {value: 'ads', title: 'Ads'},
  {value: 'uaBrowser', title: 'Browser'},
  {value: 'uaBrowserVersion', title: 'Browser Version'},
  {value: 'uaOS', title: 'OS'}
]
